#!/usr/bin/env bash
set -euo pipefail

# ROMs, intermediate files and files generated by the IAR compiler

cd "$(dirname "$0")"

rm -rf ./0_Builds ../../0_Builds/obj/JIO_MSX-DOS
rm -f drv_jio.r01 drv_jio_c.as rdate.inc
